var chrome,$,itemData={},winIds=[],Asins=null,al=0,C_win=null;
try{var stop=function(){C_win=Asins=null;al=0;itemData={};for(var a=0;a<winIds.length;a++)try{chrome.windows.remove(winIds[a])}catch(b){console.log(b)}winIds=[]},executeScriptWithjQuery=function(a,b){chrome.tabs.executeScript(a,{file:"jQuery3_1.js"},function(c){chrome.tabs.executeScript(a,{file:b})})},openPage=function(){chrome.windows.create({focused:!1,width:1,height:1,url:"https://www.amazon.co.jp/dp/"+Asins[al]},function(a){winIds.push(a.id);executeScriptWithjQuery(a.tabs[0].id,"scraping/getdata.js");
chrome.windows.update(C_win,{focused:!0})})},test_Deferred=function(a,b){var c=$.Deferred();try{chrome.windows.create({focused:!1,url:a,width:1,height:1},function(a){winIds.push(a.id);executeScriptWithjQuery(a.tabs[0].id,b);chrome.windows.update(C_win,{focused:!0});c.resolve(a)})}catch(d){c.reject("test_Deferred\u306b\u3066\u30a8\u30e9\u30fc\n"+d)}return c.promise()},lastAction=function(){if(void 0!==itemData.totalcost&&void 0!==itemData.rank&&void 0!==itemData.rival){itemData.SpreadsheetId="lbpodihdhpepnobmhpefflmeojlmojee"===
chrome.runtime.id?"1f-N20_rVblZFwnsskUs2zA5pCijSvLXCsnKZ59gP3n0":"1psk6Bvn47WozfiqDGSatPr0uac7qFjtYB9cWPPtBhMc";console.log("\u6700\u7d42\u30c7\u30fc\u30bf");console.log(itemData);console.log(winIds);for(var a=0;a<winIds.length;a++)chrome.windows.remove(winIds[a]);winIds=[];$.ajax({type:"POST",url:"https://script.google.com/macros/s/AKfycbzpP61dEEQBwOk231LSSxjySDklx0XbOoE5WHoxjgmQqIU8RiI/exec",cache:!0,data:itemData,timeout:1E4}).always(function(a){itemData={};Asins?(al++,al<=Asins.length-1?setTimeout(openPage,
1E4*Math.random()):(alert("\u5168\u3066\u306eASIN\u306e\u8a18\u5165\u304c\u5b8c\u4e86\u3057\u307e\u3057\u305f"),console.log(a),stop())):(alert(a),stop())})}};chrome.browserAction.onClicked.addListener(function(a){if(C_win)confirm("\u5b9f\u884c\u4e2d\u3067\u3059\u3002\u4e2d\u65ad\u3057\u307e\u3059\u304b\uff1f")&&stop();else if(chrome.windows.getCurrent({},function(a){C_win=a.id}),itemData={},winIds=[],a.url.match(/https\:\/\/www\.amazon\.co\.jp\/.*dp\//))executeScriptWithjQuery(a.id,"scraping/getdata.js");
else if(-1!==a.url.indexOf("mnrate.com"))executeScriptWithjQuery(a.id,"scraping/only_monorate.js");else if(a.url.match(/https\:\/\/www\.amazon\.co\.jp\/.*marketplaceID\=.*/)||a.url.match(/https\:\/\/www\.amazon\.co\.jp\/.*keywords\=.*/))executeScriptWithjQuery(a.id,"scraping/getProducts.js");else{var b=function(){var a=prompt("\u4e00\u62ec\u3067\u5165\u529b\u3057\u305f\u3044ASIN\u3092\n\u30ab\u30f3\u30de(,)\n\u6539\u884c\n\u30b9\u30da\u30fc\u30b9\n\u306e\u3044\u305a\u308c\u304b\u3067\u533a\u5207\u3063\u3066\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044");
a&&(a=a.replace(/[,\s]/g,"\n"),confirm("\u5165\u529b\u3057\u305fASIN\u4e00\u89a7\n\n"+a+"\n\n\u3053\u308c\u3089\u3092\u30b7\u30fc\u30c8\u306b\u8a18\u5165\u3057\u307e\u3059\u304b\uff1f\n\n\u203b\u5168\u3066\u8a18\u5165\u5b8c\u4e86\u307e\u3067\u306b"+Math.ceil(20*a.split(/\n/).length/60)+"\u5206\u7a0b\u304b\u304b\u308a\u307e\u3059\u3002\u3054\u6ce8\u610f\u304f\u3060\u3055\u3044\u3002")&&(Asins=a.split(/\n/),al=0,openPage()))};"lbpodihdhpepnobmhpefflmeojlmojee"===chrome.runtime.id?a.url.match(/https\:\/\/sellercentral\-japan\.amazon\.com\/fba\/profitabilitycalculator\/index/)?
executeScriptWithjQuery(a.id,"clerical_work/Ichibuhenkin-checker.js"):a.url.match(/https\:\/\/amc\.busoken\.com\/wp-admin\/edit.php\?.*post_type\=shop_order.*/)?executeScriptWithjQuery(a.id,"clerical_work/orderStatus.js"):a.url.match(/https\:\/\/amc\.busoken\.com\/wp-admin\/admin.php\?.*page\=woocommerce\-points\-and\-rewards.*/)?executeScriptWithjQuery(a.id,"clerical_work/shop_price_resset.js"):b():b()}});chrome.runtime.onMessage.addListener(function(a,b,c){a.pageResponse.want_itemData?c({itemData:itemData}):
(itemData=Object.assign(itemData,a.pageResponse),"stop"===itemData.nextActionName?stop():"sellerCheck"===itemData.nextActionName?(itemData.nextActionName=null,console.log("start"),test_Deferred("https://www.amazon.co.jp/gp/offer-listing/"+itemData.asin+"/ref=olp_f_new?ie=UTF8&f_new=true&f_primeEligible=true&shipPromoFilter=1","scraping/sellerCheck.js"),test_Deferred("http://mnrate.com/item/aid/"+itemData.asin,"scraping/monorate.js")):"calc"===itemData.nextActionName?(console.log("calc"),test_Deferred("https://sellercentral-japan.amazon.com/fba/profitabilitycalculator/index?lang=ja_JP&asin="+
itemData.asin,"scraping/calculatorpage.js")):"openPage"===itemData.nextActionName&&(itemData.nextActionName=null,Asins=itemData.Asins,al=0,openPage()),lastAction())})}catch(a){console.log(a),alert(a)}